# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20161227_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес ссылки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_items_set', to='menu.Item', verbose_name='Родительский пункт меню')),
            ],
            options={
                'verbose_name_plural': 'Menu items',
                'verbose_name': 'Menu item',
            },
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
