# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20161228_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=250, verbose_name='Адрес ссылки'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Меню'),
        ),
    ]
